quarkus.langchain4j.chat-model.provider=ollama
quarkus.langchain4j.embedding-model.provider=ollama

# Configura a URL base do servidor Ollama
quarkus.langchain4j.ollama.base-url=http://localhost:11434/

# lmstudio
quarkus.langchain4j.openai.base-url=http://localhost:1234/v1

# Define o ID do modelo que o Langchain4j irá invocar no Ollama
# Na aula usou o gpt-oss:20b
quarkus.langchain4j.ollama.chat-model.model-id=qwen2.5:0.5b

# LM Studio does not require a real API key, but a placeholder is usually expected by the client
quarkus.langchain4j.openai.api-key=lm-studio
# llm model on lmstudio
quarkus.langchain4j.openai.chat-model.model-name=deepseek-r1-distill-qwen-1.5b

# Define um timeout para a chamada
quarkus.langchain4j.ollama.timeout=120s
quarkus.langchain4j.openai.timeout=120s

# O Easy-RAG irá ler todos os arquivos neste local na inicialização
quarkus.langchain4j.easy-rag.path=src/main/resources/rag
