quarkus.langchain4j.chat-model.provider=ollama
quarkus.langchain4j.embedding-model.provider=ollama

# Configura a URL base do servidor Ollama
quarkus.langchain4j.ollama.base-url=http://localhost:11434/

# lmstudio
quarkus.langchain4j.openai.base-url=http://localhost:1234/v1

# Define o ID do modelo que o Langchain4j irá invocar no Ollama
# Na aula usou o gpt-oss:20b
quarkus.langchain4j.ollama.chat-model.model-id=qwen2.5:0.5b

# LM Studio does not require a real API key, but a placeholder is usually expected by the client
quarkus.langchain4j.openai.api-key=lm-studio
# llm model on lmstudio
quarkus.langchain4j.openai.chat-model.model-name=deepseek-r1-distill-qwen-1.5b

# Define um timeout para a chamada
quarkus.langchain4j.ollama.timeout=240s
quarkus.langchain4j.openai.timeout=240s

# O Easy-RAG irá ler todos os arquivos neste local na inicialização
# quarkus.langchain4j.easy-rag.path=src/main/resources/rag

# quarkus.langchain4j.easy-rag.max-segment-size=100
# quarkus.langchain4j.easy-rag.max-overlap-size=20

# -- Configuracao do Embedding Model --
quarkus.langchain4j.ollama.embedding-model.model-id=nomic-embed-text

quarkus.langchain4j.openai.embedding-model.enabled=true
quarkus.langchain4j.openai.embedding-model.model-name=text-embedding-nomic-embed-text-v1.5

# -- Configuração do PgVector --
quarkus.langchain4j.pgvector.register-vector-pg-extension=true
quarkus.langchain4j.pgvector.dimension=768
quarkus.langchain4j.pgvector.table=travel_embeddings
quarkus.langchain4j.pgvector.drop-table-first=true

# -- configuracao de logging do langchain4j --
quarkus.langchain4j.log-requests=true
quarkus.langchain4j.log-responses=true

# Define um cliente chamado "booking-server" que será usado para enviar mensagens para o modelo de chat
quarkus.langchain4j.mcp.booking-server.transport-type=http
quarkus.langchain4j.mcp.booking-server.url=http://localhost:8081/mcp/sse/

# timeout para o cliente booking-server
quarkus.langchain4j.mcp.booking-server.timeout=60s

quarkus.langchain4j.mcp.booking-server.log-requests=true
quarkus.langchain4j.mcp.booking-server.log-responses=true